[build]
  command = """
    npm install &&
    mkdir -p functions/data &&
    cp data/items.json functions/data/ &&
    cd functions && npm install
  """
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/data/items.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 